image: maven:3-eclipse-temurin-21

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Cache location for Sonar analysis
  GIT_DEPTH: "0"  # Fetch all branches for accurate analysis

stages:
  - build-sonar

build-sonar:
  stage: build-sonar
  tags:
    - hva
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - echo "SONAR_HOST_URL=$SONAR_HOST_URL"
    - echo "SONAR_TOKEN=${SONAR_TOKEN:0:5}*****"  # Mask the token
    - cd backend-java
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'
